// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Company.proto

package gdcp.test.probuf;

public final class CompanyEntity {
  private CompanyEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CompanyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint64 id = 1;
    /**
     * <code>optional uint64 id = 1;</code>
     *
     * <pre>
     *id    有一点需要说明，java_outer_classname不能喝message名字相同，比如这里java_outer_classname不能为Company
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional uint64 id = 1;</code>
     *
     * <pre>
     *id    有一点需要说明，java_outer_classname不能喝message名字相同，比如这里java_outer_classname不能为Company
     * </pre>
     */
    long getId();

    // repeated .Employee employees = 2;
    /**
     * <code>repeated .Employee employees = 2;</code>
     */
    java.util.List<gdcp.test.probuf.EmployeeEntity.Employee> 
        getEmployeesList();
    /**
     * <code>repeated .Employee employees = 2;</code>
     */
    gdcp.test.probuf.EmployeeEntity.Employee getEmployees(int index);
    /**
     * <code>repeated .Employee employees = 2;</code>
     */
    int getEmployeesCount();
    /**
     * <code>repeated .Employee employees = 2;</code>
     */
    java.util.List<? extends gdcp.test.probuf.EmployeeEntity.EmployeeOrBuilder> 
        getEmployeesOrBuilderList();
    /**
     * <code>repeated .Employee employees = 2;</code>
     */
    gdcp.test.probuf.EmployeeEntity.EmployeeOrBuilder getEmployeesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Company}
   */
  public static final class Company extends
      com.google.protobuf.GeneratedMessage
      implements CompanyOrBuilder {
    // Use Company.newBuilder() to construct.
    private Company(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Company(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Company defaultInstance;
    public static Company getDefaultInstance() {
      return defaultInstance;
    }

    public Company getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Company(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                employees_ = new java.util.ArrayList<gdcp.test.probuf.EmployeeEntity.Employee>();
                mutable_bitField0_ |= 0x00000002;
              }
              employees_.add(input.readMessage(gdcp.test.probuf.EmployeeEntity.Employee.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          employees_ = java.util.Collections.unmodifiableList(employees_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gdcp.test.probuf.CompanyEntity.internal_static_Company_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gdcp.test.probuf.CompanyEntity.internal_static_Company_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gdcp.test.probuf.CompanyEntity.Company.class, gdcp.test.probuf.CompanyEntity.Company.Builder.class);
    }

    public static com.google.protobuf.Parser<Company> PARSER =
        new com.google.protobuf.AbstractParser<Company>() {
      public Company parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Company(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Company> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional uint64 id = 1;</code>
     *
     * <pre>
     *id    有一点需要说明，java_outer_classname不能喝message名字相同，比如这里java_outer_classname不能为Company
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 id = 1;</code>
     *
     * <pre>
     *id    有一点需要说明，java_outer_classname不能喝message名字相同，比如这里java_outer_classname不能为Company
     * </pre>
     */
    public long getId() {
      return id_;
    }

    // repeated .Employee employees = 2;
    public static final int EMPLOYEES_FIELD_NUMBER = 2;
    private java.util.List<gdcp.test.probuf.EmployeeEntity.Employee> employees_;
    /**
     * <code>repeated .Employee employees = 2;</code>
     */
    public java.util.List<gdcp.test.probuf.EmployeeEntity.Employee> getEmployeesList() {
      return employees_;
    }
    /**
     * <code>repeated .Employee employees = 2;</code>
     */
    public java.util.List<? extends gdcp.test.probuf.EmployeeEntity.EmployeeOrBuilder> 
        getEmployeesOrBuilderList() {
      return employees_;
    }
    /**
     * <code>repeated .Employee employees = 2;</code>
     */
    public int getEmployeesCount() {
      return employees_.size();
    }
    /**
     * <code>repeated .Employee employees = 2;</code>
     */
    public gdcp.test.probuf.EmployeeEntity.Employee getEmployees(int index) {
      return employees_.get(index);
    }
    /**
     * <code>repeated .Employee employees = 2;</code>
     */
    public gdcp.test.probuf.EmployeeEntity.EmployeeOrBuilder getEmployeesOrBuilder(
        int index) {
      return employees_.get(index);
    }

    private void initFields() {
      id_ = 0L;
      employees_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      for (int i = 0; i < employees_.size(); i++) {
        output.writeMessage(2, employees_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      for (int i = 0; i < employees_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, employees_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gdcp.test.probuf.CompanyEntity.Company parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gdcp.test.probuf.CompanyEntity.Company parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gdcp.test.probuf.CompanyEntity.Company parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gdcp.test.probuf.CompanyEntity.Company parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gdcp.test.probuf.CompanyEntity.Company parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gdcp.test.probuf.CompanyEntity.Company parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gdcp.test.probuf.CompanyEntity.Company parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gdcp.test.probuf.CompanyEntity.Company parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gdcp.test.probuf.CompanyEntity.Company parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gdcp.test.probuf.CompanyEntity.Company parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gdcp.test.probuf.CompanyEntity.Company prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Company}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gdcp.test.probuf.CompanyEntity.CompanyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gdcp.test.probuf.CompanyEntity.internal_static_Company_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gdcp.test.probuf.CompanyEntity.internal_static_Company_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gdcp.test.probuf.CompanyEntity.Company.class, gdcp.test.probuf.CompanyEntity.Company.Builder.class);
      }

      // Construct using gdcp.test.probuf.CompanyEntity.Company.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEmployeesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (employeesBuilder_ == null) {
          employees_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          employeesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gdcp.test.probuf.CompanyEntity.internal_static_Company_descriptor;
      }

      public gdcp.test.probuf.CompanyEntity.Company getDefaultInstanceForType() {
        return gdcp.test.probuf.CompanyEntity.Company.getDefaultInstance();
      }

      public gdcp.test.probuf.CompanyEntity.Company build() {
        gdcp.test.probuf.CompanyEntity.Company result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gdcp.test.probuf.CompanyEntity.Company buildPartial() {
        gdcp.test.probuf.CompanyEntity.Company result = new gdcp.test.probuf.CompanyEntity.Company(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (employeesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            employees_ = java.util.Collections.unmodifiableList(employees_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.employees_ = employees_;
        } else {
          result.employees_ = employeesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gdcp.test.probuf.CompanyEntity.Company) {
          return mergeFrom((gdcp.test.probuf.CompanyEntity.Company)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gdcp.test.probuf.CompanyEntity.Company other) {
        if (other == gdcp.test.probuf.CompanyEntity.Company.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (employeesBuilder_ == null) {
          if (!other.employees_.isEmpty()) {
            if (employees_.isEmpty()) {
              employees_ = other.employees_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEmployeesIsMutable();
              employees_.addAll(other.employees_);
            }
            onChanged();
          }
        } else {
          if (!other.employees_.isEmpty()) {
            if (employeesBuilder_.isEmpty()) {
              employeesBuilder_.dispose();
              employeesBuilder_ = null;
              employees_ = other.employees_;
              bitField0_ = (bitField0_ & ~0x00000002);
              employeesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEmployeesFieldBuilder() : null;
            } else {
              employeesBuilder_.addAllMessages(other.employees_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gdcp.test.probuf.CompanyEntity.Company parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gdcp.test.probuf.CompanyEntity.Company) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint64 id = 1;
      private long id_ ;
      /**
       * <code>optional uint64 id = 1;</code>
       *
       * <pre>
       *id    有一点需要说明，java_outer_classname不能喝message名字相同，比如这里java_outer_classname不能为Company
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 id = 1;</code>
       *
       * <pre>
       *id    有一点需要说明，java_outer_classname不能喝message名字相同，比如这里java_outer_classname不能为Company
       * </pre>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       *
       * <pre>
       *id    有一点需要说明，java_outer_classname不能喝message名字相同，比如这里java_outer_classname不能为Company
       * </pre>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       *
       * <pre>
       *id    有一点需要说明，java_outer_classname不能喝message名字相同，比如这里java_outer_classname不能为Company
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // repeated .Employee employees = 2;
      private java.util.List<gdcp.test.probuf.EmployeeEntity.Employee> employees_ =
        java.util.Collections.emptyList();
      private void ensureEmployeesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          employees_ = new java.util.ArrayList<gdcp.test.probuf.EmployeeEntity.Employee>(employees_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          gdcp.test.probuf.EmployeeEntity.Employee, gdcp.test.probuf.EmployeeEntity.Employee.Builder, gdcp.test.probuf.EmployeeEntity.EmployeeOrBuilder> employeesBuilder_;

      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public java.util.List<gdcp.test.probuf.EmployeeEntity.Employee> getEmployeesList() {
        if (employeesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(employees_);
        } else {
          return employeesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public int getEmployeesCount() {
        if (employeesBuilder_ == null) {
          return employees_.size();
        } else {
          return employeesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public gdcp.test.probuf.EmployeeEntity.Employee getEmployees(int index) {
        if (employeesBuilder_ == null) {
          return employees_.get(index);
        } else {
          return employeesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public Builder setEmployees(
          int index, gdcp.test.probuf.EmployeeEntity.Employee value) {
        if (employeesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeesIsMutable();
          employees_.set(index, value);
          onChanged();
        } else {
          employeesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public Builder setEmployees(
          int index, gdcp.test.probuf.EmployeeEntity.Employee.Builder builderForValue) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.set(index, builderForValue.build());
          onChanged();
        } else {
          employeesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public Builder addEmployees(gdcp.test.probuf.EmployeeEntity.Employee value) {
        if (employeesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeesIsMutable();
          employees_.add(value);
          onChanged();
        } else {
          employeesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public Builder addEmployees(
          int index, gdcp.test.probuf.EmployeeEntity.Employee value) {
        if (employeesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeesIsMutable();
          employees_.add(index, value);
          onChanged();
        } else {
          employeesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public Builder addEmployees(
          gdcp.test.probuf.EmployeeEntity.Employee.Builder builderForValue) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.add(builderForValue.build());
          onChanged();
        } else {
          employeesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public Builder addEmployees(
          int index, gdcp.test.probuf.EmployeeEntity.Employee.Builder builderForValue) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.add(index, builderForValue.build());
          onChanged();
        } else {
          employeesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public Builder addAllEmployees(
          java.lang.Iterable<? extends gdcp.test.probuf.EmployeeEntity.Employee> values) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          super.addAll(values, employees_);
          onChanged();
        } else {
          employeesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public Builder clearEmployees() {
        if (employeesBuilder_ == null) {
          employees_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          employeesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public Builder removeEmployees(int index) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.remove(index);
          onChanged();
        } else {
          employeesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public gdcp.test.probuf.EmployeeEntity.Employee.Builder getEmployeesBuilder(
          int index) {
        return getEmployeesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public gdcp.test.probuf.EmployeeEntity.EmployeeOrBuilder getEmployeesOrBuilder(
          int index) {
        if (employeesBuilder_ == null) {
          return employees_.get(index);  } else {
          return employeesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public java.util.List<? extends gdcp.test.probuf.EmployeeEntity.EmployeeOrBuilder> 
           getEmployeesOrBuilderList() {
        if (employeesBuilder_ != null) {
          return employeesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(employees_);
        }
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public gdcp.test.probuf.EmployeeEntity.Employee.Builder addEmployeesBuilder() {
        return getEmployeesFieldBuilder().addBuilder(
            gdcp.test.probuf.EmployeeEntity.Employee.getDefaultInstance());
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public gdcp.test.probuf.EmployeeEntity.Employee.Builder addEmployeesBuilder(
          int index) {
        return getEmployeesFieldBuilder().addBuilder(
            index, gdcp.test.probuf.EmployeeEntity.Employee.getDefaultInstance());
      }
      /**
       * <code>repeated .Employee employees = 2;</code>
       */
      public java.util.List<gdcp.test.probuf.EmployeeEntity.Employee.Builder> 
           getEmployeesBuilderList() {
        return getEmployeesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gdcp.test.probuf.EmployeeEntity.Employee, gdcp.test.probuf.EmployeeEntity.Employee.Builder, gdcp.test.probuf.EmployeeEntity.EmployeeOrBuilder> 
          getEmployeesFieldBuilder() {
        if (employeesBuilder_ == null) {
          employeesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gdcp.test.probuf.EmployeeEntity.Employee, gdcp.test.probuf.EmployeeEntity.Employee.Builder, gdcp.test.probuf.EmployeeEntity.EmployeeOrBuilder>(
                  employees_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          employees_ = null;
        }
        return employeesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Company)
    }

    static {
      defaultInstance = new Company(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Company)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Company_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Company_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCompany.proto\032\016Employee.proto\"3\n\007Compa" +
      "ny\022\n\n\002id\030\001 \001(\004\022\034\n\temployees\030\002 \003(\0132\t.Empl" +
      "oyeeB!\n\020gdcp.test.probufB\rCompanyEntity"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Company_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Company_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Company_descriptor,
              new java.lang.String[] { "Id", "Employees", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gdcp.test.probuf.EmployeeEntity.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
